# Generated by Django 5.2.7 on 2026-07-01 23:15

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format +989xxxxxxxxx",
                        regex="^\\+989\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="national_code",
            field=models.CharField(
                default="0250704961",
                max_length=10,
                unique=True,
                validators=[accounts.validators.validate_national_code],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.IntegerField(
                choices=[(1, "Customer"), (2, "Admin"), (3, "Superuser")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters are allowed.", regex="^[A-Za-zآ-ی ]+$"
                    ),
                    django.core.validators.MinLengthValidator(4),
                ],
            ),
        ),
    ]
