# Generated by Django 5.2.7 on 2026-07-01 23:15

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_is_admin_remove_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_code",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[accounts.validators.validate_national_code],
            ),
        ),
    ]
