# Generated by Django 5.2.7 on 2026-05-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
